### ISSUE TITLE
Ajouter le player Auto (Pastebin) dans l'archive

### ISSUE THREAD

**Issue by lanzorg** [lesalkodiques/lesalkodiques.github.io#1]
Salut lesalkodiques,

Je me demandais pourquoi le player nommé "Auto" dans le tutoriel n'est tout simplement pas mis dans l'archive ?

Pourquoi le faire manuellement ?

**Comment by alKODIque** [comment]
Parce que c'est justement la seule façon de créer ce type de player.
C'est impossible de le mettre dans cet archive puisque ce player est basé sur des addons déjà installé sur nos systèmes respectifs. En résumé: il ne se crée pas au même emplacement que ceux proposés dans l'archive. Le partager a d'autres ne fonctionnerait tout simplement pas.
Le tuto proposé vous indique comment, donc, vous en créer un vous-même. Je crois que c'est déjà bien, non? :P
